package org.graphiks.webgpu.suite

/** The stable identity of every foundation case. The enum is the expected catalogue. */
enum class AcidCaseId(val id: String) {
    BuffersMappedAtCreation("buffers.mapped-at-creation"),
    TransfersCopyOffsets("transfers.copy-offsets"),
    TransfersWriteOffsets("transfers.write-offsets"),
    TransfersWriteRemaining("transfers.write-remaining"),
    BuffersPartialMapRemap("buffers.partial-map-remap"),
    ComputeAutoLayoutConstants("compute.auto-layout-constants"),
    ComputeExplicitLayoutEntrypoint("compute.explicit-layout-entrypoint"),
    ErrorsEmptyScope("errors.empty-scope"),
    ErrorsInvalidBufferUsage("errors.invalid-buffer-usage"),
    ErrorsMapAlignment("errors.map-alignment"),
    BuffersMapDestroyed("buffers.map-destroyed"),
    BuffersZeroInitialized("buffers.zero-initialized"),
    BuffersMapWriteRoundTrip("buffers.map-write-roundtrip"),
    TransfersClearBufferRange("transfers.clear-buffer-range"),
    TransfersCopyRemaining("transfers.copy-remaining"),
    BindingsBufferRange("bindings.buffer-range"),
    BindingsDynamicUniformOffsets("bindings.dynamic-uniform-offsets"),
    ComputeIndirectDispatch("compute.indirect-dispatch"),
    ComputeOrderedPasses("compute.ordered-passes"),
    TransfersWriteTextureTightRows("transfers.write-texture-tight-rows"),
    TransfersUploadPaddedRows("transfers.upload-padded-rows"),
    TransfersReadbackOffsetPadding("transfers.readback-offset-padding"),
    TransfersArrayLayerStride("transfers.array-layer-stride"),
    TransfersWriteSubrectangle("transfers.write-subrectangle"),
    TransfersTextureRegionCopy("transfers.texture-region-copy"),
    TransfersMipLevelCopy("transfers.mip-level-copy"),
    TransfersVolumeSlices("transfers.volume-slices"),
}
